ASSIGNMENT 2

In [1]:
import pandas as pd

In [5]:
data_users = pd.read_csv("user_reviews.csv")
data_movies = pd.read_csv("movie_genres.csv")

In [19]:
data_users.head()

,Unnamed: 0,User,The Net,Happily N'Ever After,Tomorrowland,American Hero,Das Boot,Final Destination 3,Licence to Kill,The Hundred-Foot Journey,...,The Martian,Micmacs,Solomon and Sheba,In the Company of Men,Silent House,Big Fish,Get Real,Trading Places,DOA: Dead or Alive,Hey Arnold! The Movie
0,0,Vincent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,Edgar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,Addilyn,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,Marlee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,Javier,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
data_movies.head()

,Unnamed: 0,movie_title,genre_action,genre_adventure,genre_animation,genre_biography,genre_comedy,genre_crime,genre_documentary,genre_drama,...,genre_mystery,genre_news,genre_reality-tv,genre_romance,genre_sci-fi,genre_short,genre_sport,genre_thriller,genre_war,genre_western
0,0,The Net,1,0,0,0,0,1,0,1,...,1,0,0,0,0,0,0,1,0,0
1,1,Happily N'Ever After,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,Tomorrowland,1,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
3,3,American Hero,1,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,4,Das Boot,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0

In [11]:
user_df = pd.DataFrame(data_users)
movie_df = pd.DataFrame(data_movies)

In [12]:
user_df.fillna(0, inplace=True)

Iteration 1/100, MSE: 12.911055790069254
Predicted rating for User 0, Movie 0: [0.07175464453978125]
Iteration 2/100, MSE: 12.905519258429678
Iteration 3/100, MSE: 12.899936076511837
Iteration 4/100, MSE: 12.894255438472513
Iteration 5/100, MSE: 12.888425066963897
Iteration 6/100, MSE: 12.882390369593454
Iteration 7/100, MSE: 12.87609352476728
Iteration 8/100, MSE: 12.869472467458856
Iteration 9/100, MSE: 12.862459741041048
Iteration 10/100, MSE: 12.854981175389877
Iteration 11/100, MSE: 12.846954343783219
Predicted rating for User 0, Movie 0: [0.06795362928552312]
Iteration 12/100, MSE: 12.83828674134207
Iteration 13/100, MSE: 12.828873615510693
Iteration 14/100, MSE: 12.818595363882853
Iteration 15/100, MSE: 12.807314396011508
Iteration 16/100, MSE: 12.794871333111562
Iteration 17/100, MSE: 12.781080392159067
Iteration 18/100, MSE: 12.765723768238145
Iteration 19/100, MSE: 12.748544790663942
Iteration 20/100, MSE: 12.729239584329507
Iteration 21/100, MSE: 12.707446918436736
Predicted rating for User 0, Movie 0: [0.06829703700395351]
Iteration 22/100, MSE: 12.682735871941885
Iteration 23/100, MSE: 12.654590892210006
Iteration 24/100, MSE: 12.62239377702578
Iteration 25/100, MSE: 12.585402081388436
Iteration 26/100, MSE: 12.542723457565078
Iteration 27/100, MSE: 12.493285508070295
Iteration 28/100, MSE: 12.435800909566844
Iteration 29/100, MSE: 12.368727913947783
Iteration 30/100, MSE: 12.290226939307237
Iteration 31/100, MSE: 12.19811494611405
Predicted rating for User 0, Movie 0: [0.13584648658421153]
Iteration 32/100, MSE: 12.089820799662963
Iteration 33/100, MSE: 11.962347012227426
Iteration 34/100, MSE: 11.81224628082465
Iteration 35/100, MSE: 11.635625135158696
Iteration 36/100, MSE: 11.428191592929997
Iteration 37/100, MSE: 11.185368335029196
Iteration 38/100, MSE: 10.90249616044018
Iteration 39/100, MSE: 10.575151931351906
Iteration 40/100, MSE: 10.199597363937206
Iteration 41/100, MSE: 9.773355831256415
Predicted rating for User 0, Movie 0: [0.8066291955336958]
Iteration 42/100, MSE: 9.29588094086344
Iteration 43/100, MSE: 8.769234324504177
Iteration 44/100, MSE: 8.198640019734302
Iteration 45/100, MSE: 7.592748199629425
Iteration 46/100, MSE: 6.963447598812
Iteration 47/100, MSE: 6.325134551528009
Iteration 48/100, MSE: 5.693475602093762
Iteration 49/100, MSE: 5.083854532747059
Iteration 50/100, MSE: 4.509811165079769
Iteration 51/100, MSE: 3.981800275991935
Predicted rating for User 0, Movie 0: [3.2878241186393633]
Iteration 52/100, MSE: 3.50650717285289
Iteration 53/100, MSE: 3.0867902874564543
Iteration 54/100, MSE: 2.7221529948140772
Iteration 55/100, MSE: 2.409540697065689
Iteration 56/100, MSE: 2.1442388722471524
Iteration 57/100, MSE: 1.920695249768464
Iteration 58/100, MSE: 1.733166097963072
Iteration 59/100, MSE: 1.576158218279967
Iteration 60/100, MSE: 1.444686469703096
Iteration 61/100, MSE: 1.3343892139334161
Predicted rating for User 0, Movie 0: [4.5736677725260275]
Iteration 62/100, MSE: 1.241547597771282
Iteration 63/100, MSE: 1.1630477354163222
Iteration 64/100, MSE: 1.0963144652721468
Iteration 65/100, MSE: 1.0392354364114882
Iteration 66/100, MSE: 0.9900864974202945
Iteration 67/100, MSE: 0.9474639712286076
Iteration 68/100, MSE: 0.9102260185527805
Iteration 69/100, MSE: 0.8774433643791575
Iteration 70/100, MSE: 0.8483586840933685
Iteration 71/100, MSE: 0.8223535404798323
Predicted rating for User 0, Movie 0: [4.379636590909496]
Iteration 72/100, MSE: 0.7989216751383792
Iteration 73/100, MSE: 0.7776475293451193
Iteration 74/100, MSE: 0.7581890079081905
Iteration 75/100, MSE: 0.7402636552864398
Iteration 76/100, MSE: 0.7236375615470702
Iteration 77/100, MSE: 0.7081164462597033
Iteration 78/100, MSE: 0.6935384783135858
Iteration 79/100, MSE: 0.679768479717899
Iteration 80/100, MSE: 0.6666932340522539
Iteration 81/100, MSE: 0.6542176781550065
Predicted rating for User 0, Movie 0: [4.153951971991621]
Iteration 82/100, MSE: 0.6422618015519423
Iteration 83/100, MSE: 0.6307581143958042
Iteration 84/100, MSE: 0.6196495732912288
Iteration 85/100, MSE: 0.6088878769317264
Iteration 86/100, MSE: 0.5984320612697996
Iteration 87/100, MSE: 0.5882473379993601
Iteration 88/100, MSE: 0.5783041312577762
Iteration 89/100, MSE: 0.5685772762812604
Iteration 90/100, MSE: 0.5590453507658639
Iteration 91/100, MSE: 0.5496901152803727
Predicted rating for User 0, Movie 0: [4.021435041510854]
Iteration 92/100, MSE: 0.5404960435490149
Iteration 93/100, MSE: 0.5314499270043515
Iteration 94/100, MSE: 0.5225405408900234
Iteration 95/100, MSE: 0.5137583615125652
Iteration 96/100, MSE: 0.5050953261154058
Iteration 97/100, MSE: 0.4965446283663045
Iteration 98/100, MSE: 0.4881005436825399
Iteration 99/100, MSE: 0.4797582796220267
Iteration 100/100, MSE: 0.47151384738857255